
#set page(width: 210mm, height: 297mm, margin: 25mm)
#set document(author: "Leonardo Bornhäußer; Tuna Cakar (Creativate Research Group)", title: "The Neural Enterprise Network (NEN): A Cluster-Based Architecture for Organizational Decision Intelligence")

// Simple heading numbering
#set heading(numbering: "1.")

// Title block
= The Neural Enterprise Network (NEN): A Cluster-Based Architecture for Organizational Decision Intelligence

*Author:* Leonardo Bornhäußer; Tuna Cakar  
*Date:* 2025-10-30

== Abstract
We introduce the Neural Enterprise Network (NEN), a cluster-based architecture for organizational decision intelligence that unifies domains (Finance, Operations, HR, ESG, Product, Market/Sales) via a shared forecast layer and governance-by-design. NEN integrates explainability and uncertainty quantification as first-class elements and targets reproducibility and compliance (EU AI Act, CSRD).

== Introduction
Organizations increasingly rely on ML for forecasting and planning, yet models are often siloed by domain. We motivate a unifying architecture that enables cross-domain learning, explainability propagation, and calibrated uncertainty for decision rules.

== Concept: Neural Enterprise Network (NEN)
NEN models an enterprise as interacting clusters. Each cluster holds domain-specific predictors; clusters exchange signals through a shared forecast layer under a Haloframe governance system (lineage, explainability, auditability).

=== Architecture Overview
#figure(
  image("../../../figures/nen_architecture_v3.png"),
  caption: "Neural Enterprise Network (NEN) — exported from the Creativate research vault."
)

== Methodology & Design Principles
- *Conceptual:* NEN structure (clusters, forecast layer).
- *Technical:* cNode platform, Haloframe governance, MLflow lineage.
- *Analytical:* Explainability (e.g., SHAP/LIME) and uncertainty (ECE/CRPS).
- *Process:* Data→Decision loop and AI readiness path.

== Experimental Design (Planned)
Prototype on synthetic/anonymized enterprise metrics across Finance, HR, and Ops. Metrics: MAE, SMAPE, ECE, CRPS. Baselines: independent per-domain vs shared-cluster models. Evaluation via the open `oss-eval` toolkit.

== Results (Placeholder)
Figures and tables generated by code. Initial demo: SMAPE evaluation and calibration plots.

== Conclusion
NEN provides a governance-ready, uncertainty-aware decision architecture that bridges ML and organizational design.

== References
// Add references here or integrate a bibliography later.
