#let title = "NEN + Uncertainty-aware XAI: A Practical Note"
#let author = "Creativate AI Studio"
#let date = datetime.today()

= +title

*Author:* +author \
*Date:* +date

== Abstract

This is a short abstract. Replace with your summary.

== Introduction

Motivation and contribution.

== Method

Sketch the Neural Enterprise Network (NEN) and uncertainty-aware explanations.

== Results

Tables and figures generated by `oss-eval`.

== Conclusion

Short and sweet.

== References

- Add references here.
