name: Paper PDF

on:
  push:
    tags:
      - "v*"        # only run on version tags (e.g. v0.1.4)

permissions:
  contents: write   # needed to attach paper.pdf to the Release

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build PDF
        run: |
          typst --version
          typst compile papers/paper1_nen_uqxai/main.typ paper.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: paper.pdf
