
name: Paper PDF
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build-paper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paper_path:
          - papers/paper1_nen_uqxai/main.typ
          - papers/paper2_cluster_forecasting/main.typ
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: typst-community/setup-typst@v3
      - name: Debug tree
        run: ls -la $(dirname "${{ matrix.paper_path }}")
      - name: Build PDF
        run: |
          out="paper-$(basename $(dirname "${{ matrix.paper_path }}")).pdf"
          typst --version
          typst compile "${{ matrix.paper_path }}" "$out"
          ls -lh "$out"
      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdfs
          path: paper-*.pdf
      - name: Attach PDFs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: paper-*.pdf
